import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'

import Stytch from '@/components/stytch'

import Navigation from './_components/navigation'

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Stytch>
      <html lang="en">
        <body className={inter.className}>
          <Navigation />
          <main >
            {children}
          </main>
        </body>
      </html>
    </Stytch>
  )
}
