import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'

import Navigation from './_components/navigation'

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <main className="h-[calc(100vh-56px)] w-full flex flex-col justify-center items-center mt-14 font-mono text-sm">
          {children}
        </main>
      </body>
    </html>
  )
}
